"""教研场景种子数据（与原 PySide6 / Web 版完全一致）。

首次启动时写入 SQLite；「重置演示数据」也回到这里。
日期字段用 day_offset(n) 相对今天生成，保证演示数据永远是「活的」。
"""
from __future__ import annotations

from .utils import day_offset as D

PROFILE = {
    "name": "江先亮",
    "title": "教授",
    "dept": "计算机科学与技术学院",
    "email": "jiangxl@university.edu.cn",
    "office": "信息楼 A-513",
}

PROJECTS = [
    {
        "id": "p1",
        "name": "基于多模态融合的社区精神分裂症早期筛查关键技术研究",
        "code": "NSFC-62176829",
        "type": "国家自然科学基金面上项目",
        "role": "主持",
        "funding": "62",
        "startDate": "2024-01-01",
        "deadline": D(78),
        "status": "在研",
        "progress": 58,
        "desc": "面向社区人群，融合面部微表情视频、语音韵律与临床量表三模态信息，构建低负担、高特异度的精神分裂症早期筛查模型，并在社区卫生中心开展多中心验证。",
        "phases": [
            {"name": "文献调研与方案设计", "dueDate": "2024-06-30", "done": True},
            {"name": "多模态数据集构建与标注", "dueDate": "2025-03-31", "done": True},
            {"name": "融合模型设计与消融实验", "dueDate": "2026-06-30", "done": True},
            {"name": "社区多中心样本验证", "dueDate": D(78), "done": False, "active": True},
            {"name": "结题材料准备", "dueDate": D(150), "done": False},
        ],
        "outcomes": [
            {"type": "期刊论文", "title": "多模态对比学习在精神分裂症早期识别中的应用", "status": "已录用", "date": "2025-11-20"},
            {"type": "期刊论文", "title": "融合语音韵律的阴性症状评估方法研究", "status": "审稿中", "date": "2026-05-12"},
            {"type": "发明专利", "title": "一种基于多模态融合的精神分裂症筛查装置", "status": "实质审查", "date": "2025-08-01"},
        ],
    },
    {
        "id": "p2",
        "name": "面向智慧养老的毫米波雷达跌倒检测算法研究",
        "code": "KJ2024-08",
        "type": "省重点研发计划",
        "role": "主持",
        "funding": "35",
        "startDate": "2024-07-01",
        "deadline": D(-9),
        "status": "验收中",
        "progress": 94,
        "desc": "针对独居老人监护场景，研究低分辨率毫米波雷达点云中的姿态表征与跌倒事件检测算法，兼顾隐私保护与部署成本。",
        "phases": [
            {"name": "雷达采集平台搭建", "dueDate": "2024-12-31", "done": True},
            {"name": "跌倒检测算法开发", "dueDate": "2025-08-31", "done": True},
            {"name": "现场数据采集与调优", "dueDate": "2026-03-31", "done": True},
            {"name": "结题验收", "dueDate": D(-9), "done": False, "active": True},
        ],
        "outcomes": [
            {"type": "期刊论文", "title": "基于点云时序建模的毫米波雷达跌倒检测", "status": "已发表", "date": "2025-09-15"},
            {"type": "软件著作权", "title": "智慧养老跌倒监测系统 V1.0", "status": "已登记", "date": "2025-04-08"},
        ],
    },
    {
        "id": "p3",
        "name": "电梯运行状态智能监测与故障预测系统",
        "code": "HX-2024-113",
        "type": "企业横向合作",
        "role": "主持",
        "funding": "48",
        "startDate": "2024-09-01",
        "deadline": D(268),
        "status": "在研",
        "progress": 71,
        "desc": "基于 IMU 传感数据与教师-学生网络方法，研究电梯关键部件退化趋势建模与故障提前预警，已在两家物业的 36 台电梯上线试运行。",
        "phases": [
            {"name": "传感数据采集与清洗", "dueDate": "2025-02-28", "done": True},
            {"name": "故障预测模型训练", "dueDate": "2025-12-31", "done": True},
            {"name": "边端部署与联调", "dueDate": D(120), "done": False, "active": True},
            {"name": "项目交付验收", "dueDate": D(268), "done": False},
        ],
        "outcomes": [
            {"type": "发明专利", "title": "基于教师学生网络的电梯故障预测方法及系统", "status": "已授权", "date": "2026-02-18"},
            {"type": "技术报告", "title": "电梯运行状态监测系统集成测试报告", "status": "已交付", "date": "2026-06-30"},
        ],
    },
    {
        "id": "p4",
        "name": "高压断路器机械缺陷声纹识别方法研究",
        "code": "SGCC-2025-0417",
        "type": "国家电网科技项目",
        "role": "参与",
        "funding": "—",
        "startDate": "2025-03-01",
        "deadline": D(96),
        "status": "在研",
        "progress": 37,
        "desc": "与电网研究院合作，研究分合闸振动声纹信号的特征提取与缺陷分类方法，作为子课题负责人承担算法设计部分。",
        "phases": [
            {"name": "声纹样本采集与标注", "dueDate": "2025-09-30", "done": True},
            {"name": "特征提取与分类模型", "dueDate": D(96), "done": False, "active": True},
            {"name": "现场验证与报告", "dueDate": D(200), "done": False},
        ],
        "outcomes": [
            {"type": "期刊论文", "title": "断路器分合闸声纹的时频特征与缺陷识别", "status": "撰写中", "date": ""},
        ],
    },
]

LITERATURE = [
    {
        "id": "l1",
        "title": "Multimodal Machine Learning: A Survey and Taxonomy",
        "authors": "Baltrušaitis T., Ahuja C., Morency L.-P.",
        "journal": "IEEE TPAMI",
        "year": "2019",
        "doi": "10.1109/TPAMI.2018.2798607",
        "tags": ["多模态融合", "方法综述"],
        "status": "已读",
        "rating": 5,
        "note": "多模态领域的奠基性综述，提出「表征—对齐—融合—翻译—共学习」五类问题的分类体系。融合章节（第 5 节）对项目 p1 的模型设计最有参考价值：早期/晚期/混合融合的权衡讨论，以及模态缺失时的鲁棒性问题——正好命中我们社区数据中量表缺失的情况，可考虑引入其提到的 modality dropout 训练策略。",
        "addedDate": D(-120),
        "direction": "多模态学习",
    },
    {
        "id": "l2",
        "title": "A Survey on Vision Transformer",
        "authors": "Han K., Wang Y., Chen H., et al.",
        "journal": "IEEE TPAMI",
        "year": "2023",
        "doi": "10.1109/TPAMI.2022.3152247",
        "tags": ["Transformer", "视觉骨干", "方法综述"],
        "status": "已读",
        "rating": 4,
        "note": "梳理 ViT 的改进脉络：数据效率、计算效率、主干结构、自监督预训练。第 4 节 Mixture-of-Experts 相关讨论与我在网络优化方向的 MoE 研究可以交叉——稀疏专家路由的思路或许能迁移到多模态融合分支上，用路由代替固定加权。",
        "addedDate": D(-95),
        "direction": "视觉模型",
    },
    {
        "id": "l3",
        "title": "Facial Action Unit Detection with Multimodal Transformer",
        "authors": "Zhou S., Li Q., et al.",
        "journal": "IEEE Transactions on Affective Computing",
        "year": "2024",
        "doi": "10.1109/TAFFC.2023.3345678",
        "tags": ["面部动作单元", "精神分裂症", "多模态融合"],
        "status": "在读",
        "rating": 4,
        "note": "AU 检测引入音频与文本模态做辅助监督，缓解单模态标注不足。与项目 p1 的「微表情 + 语音」路线高度契合。关键点：跨模态注意力的对齐方式采用的是对比损失而非简单拼接，值得在消融实验里作为 baseline 之一。待补：它的数据集 (BP4D+) 与我们的社区样本在人群分布上差异较大，泛化性需要验证。",
        "addedDate": D(-30),
        "direction": "精神分裂症早筛",
    },
    {
        "id": "l4",
        "title": "Radar-based Human Activity Recognition: A Comprehensive Review",
        "authors": "Li X., He Y., Jing X.",
        "journal": "IEEE Sensors Journal",
        "year": "2023",
        "doi": "10.1109/JSEN.2023.3254901",
        "tags": ["毫米波雷达", "跌倒检测", "行为识别"],
        "status": "已读",
        "rating": 5,
        "note": "系统综述了雷达人体感知的信号处理链路与常用网络结构。表 3 汇总了各类跌倒检测方法的公开数据集与指标（准确率普遍在 92%~98%），可作为项目 p2 验收报告里的对标基线。注意作者指出跨房间场景下性能下降明显，提示我们部署时要强调房间级校准。",
        "addedDate": D(-70),
        "direction": "雷达感知",
    },
    {
        "id": "l5",
        "title": "Teacher-Student Networks for Anomaly Detection in Industrial Signals",
        "authors": "Wang H., Xu J., et al.",
        "journal": "IEEE Transactions on Industrial Informatics",
        "year": "2024",
        "doi": "10.1109/TII.2024.3381122",
        "tags": ["教师学生网络", "异常检测", "电梯故障预测"],
        "status": "在读",
        "rating": 4,
        "note": "教师-学生范式用于无监督异常检测：教师网络在正常样本上预训练，学生网络在学习过程中对异常样本产生更大的响应偏差，以此作为异常分数。与项目 p3 的电梯故障预测思路一致。作者的损失设计（多尺度特征蒸馏）比单尺度更稳，计划复现后作为对比方法。",
        "addedDate": D(-18),
        "direction": "故障预测",
    },
    {
        "id": "l6",
        "title": "Sparse Mixture-of-Experts for Efficient Multi-Domain Learning",
        "authors": "Chen Z., Shen Y., et al.",
        "journal": "NeurIPS",
        "year": "2024",
        "doi": "arXiv:2405.11831",
        "tags": ["MoE", "多任务学习", "多模态融合"],
        "status": "未读",
        "rating": 3,
        "note": "待读。据摘要，作者将 MoE 用于多域数据的稀疏激活，缓解多任务间的负迁移。计划本周精读，评估其路由机制能否用于 p1 的三模态融合与 p3 的多任务（身份识别 + 状态检测）联合建模。",
        "addedDate": D(-6),
        "direction": "多任务学习",
    },
]

COURSES = [
    {
        "id": "c1",
        "name": "计算机网络",
        "code": "CS301",
        "semester": "2026 春",
        "students": 86,
        "credits": 3.5,
        "hours": 56,
        "color": "linear-gradient(135deg,#0c6b3d,#189d5b)",
        "intro": "面向高年级本科生的专业核心课，覆盖自顶向下的五层模型，重点讲解 TCP/IP 协议栈、拥塞控制与网络性能分析。",
        "syllabus": [
            {"chapter": "第 1 章 计算机网络概述", "hours": "4", "type": "讲授", "point": "体系结构、性能指标"},
            {"chapter": "第 2 章 应用层", "hours": "6", "type": "讲授", "point": "HTTP/DNS/P2P"},
            {"chapter": "第 3 章 运输层", "hours": "10", "type": "讲授 + 实验", "point": "TCP 可靠传输、拥塞控制"},
            {"chapter": "第 4 章 网络层", "hours": "12", "type": "讲授", "point": "IP、路由算法、SDN"},
            {"chapter": "第 5 章 链路层与局域网", "hours": "8", "type": "讲授 + 实验", "point": "以太网、交换机"},
            {"chapter": "第 6 章 无线与移动网络", "hours": "6", "type": "讲授", "point": "802.11、移动 IP"},
            {"chapter": "第 7 章 网络安全", "hours": "6", "type": "讲授", "point": "加密、TLS、防火墙"},
            {"chapter": "课程设计与复习", "hours": "4", "type": "实践", "point": "Socket 编程项目"},
        ],
        "materials": [
            {"type": "教学大纲", "name": "计算机网络-教学大纲-2026春.pdf", "size": "320 KB", "date": D(-140)},
            {"type": "课件", "name": "第03讲-运输层与TCP拥塞控制.pptx", "size": "8.4 MB", "date": D(-14)},
            {"type": "课件", "name": "第04讲-网络层与路由算法.pptx", "size": "6.1 MB", "date": D(-7)},
            {"type": "案例", "name": "案例-TCP BBRv3 拥塞控制实测分析.pdf", "size": "1.2 MB", "date": D(-5)},
            {"type": "实验", "name": "实验指导-基于 Wireshark 的协议分析.pdf", "size": "780 KB", "date": D(-30)},
        ],
        # 学生公开页：长期开放（不设时间窗口）
        "published": True,
        "openFrom": "",
        "openUntil": "",
    },
    {
        "id": "c2",
        "name": "机器学习导论",
        "code": "CS405",
        "semester": "2026 春",
        "students": 62,
        "credits": 3,
        "hours": 48,
        "color": "linear-gradient(135deg,#5b3fd1,#7c5cf0)",
        "intro": "研究生学位课。以「模型—优化—泛化」为主线，讲解监督学习、无监督学习与深度学习方法，强调数学推导与动手实现。",
        "syllabus": [
            {"chapter": "第 1 章 机器学习概述", "hours": "3", "type": "讲授", "point": "学习范式与基本概念"},
            {"chapter": "第 2 章 线性模型", "hours": "6", "type": "讲授", "point": "回归、分类、正则化"},
            {"chapter": "第 3 章 支持向量机", "hours": "5", "type": "讲授", "point": "对偶、核方法"},
            {"chapter": "第 4 章 神经网络与反向传播", "hours": "8", "type": "讲授 + 实验", "point": "BP 推导"},
            {"chapter": "第 5 章 卷积与循环网络", "hours": "8", "type": "讲授", "point": "CNN/RNN"},
            {"chapter": "第 6 章 注意力与 Transformer", "hours": "8", "type": "讲授", "point": "Self-Attention、MoE"},
            {"chapter": "第 7 章 无监督与自监督学习", "hours": "6", "type": "讲授", "point": "聚类、对比学习"},
            {"chapter": "课程项目答辩", "hours": "4", "type": "实践", "point": "选题与复现"},
        ],
        "materials": [
            {"type": "教学大纲", "name": "机器学习导论-教学大纲-2026春.pdf", "size": "286 KB", "date": D(-140)},
            {"type": "课件", "name": "第06讲-注意力机制与Transformer.pptx", "size": "11.2 MB", "date": D(-10)},
            {"type": "案例", "name": "案例-从零实现多头注意力机制.ipynb", "size": "240 KB", "date": D(-9)},
            {"type": "课件", "name": "第05讲-卷积神经网络.pptx", "size": "9.7 MB", "date": D(-18)},
        ],
        # 学生公开页：本学期教学周期内开放（时间窗口示例）
        "published": True,
        "openFrom": D(-40),
        "openUntil": D(90),
    },
    {
        "id": "c3",
        "name": "Python 程序设计",
        "code": "CS102",
        "semester": "2026 秋",
        "students": 124,
        "credits": 3,
        "hours": 48,
        "color": "linear-gradient(135deg,#0b7268,#0d9488)",
        "intro": "面向低年级的编程入门课，以项目驱动方式讲解 Python 语法、数据结构与常用库，培养计算思维与工程习惯。",
        "syllabus": [
            {"chapter": "第 1 章 初识 Python", "hours": "4", "type": "讲授", "point": "环境、变量、输入输出"},
            {"chapter": "第 2 章 流程控制", "hours": "6", "type": "讲授", "point": "分支与循环"},
            {"chapter": "第 3 章 函数与模块", "hours": "6", "type": "讲授", "point": "封装与复用"},
            {"chapter": "第 4 章 数据结构", "hours": "8", "type": "讲授 + 实验", "point": "列表/字典/集合"},
            {"chapter": "第 5 章 文件与异常", "hours": "6", "type": "讲授", "point": "IO 与错误处理"},
            {"chapter": "第 6 章 面向对象", "hours": "8", "type": "讲授", "point": "类与继承"},
            {"chapter": "第 7 章 数据分析入门", "hours": "6", "type": "讲授", "point": "NumPy/Pandas"},
            {"chapter": "综合项目", "hours": "4", "type": "实践", "point": "小型应用开发"},
        ],
        "materials": [
            {"type": "教学大纲", "name": "Python程序设计-教学大纲-2026秋.pdf", "size": "298 KB", "date": D(-12)},
            {"type": "课件", "name": "第01讲-Python环境与基础语法.pptx", "size": "5.3 MB", "date": D(-8)},
        ],
        # 学生公开页：暂未开放（教师手动关闭态示例）
        "published": False,
        "openFrom": "",
        "openUntil": "",
    },
]

STUDENTS = [
    {
        "id": "s1",
        "name": "李明",
        "degree": "硕士",
        "grade": "2024 级",
        "direction": "多模态情感计算",
        "email": "liming24@university.edu.cn",
        "thesisTitle": "面向社区筛查的多模态情绪状态评估方法研究",
        "stage": "中期检查",
        "progress": 55,
        "nextMeeting": D(2),
        "milestones": [
            {"name": "开题报告", "date": "2025-05-20", "done": True},
            {"name": "文献综述", "date": "2025-10-15", "done": True},
            {"name": "方法设计与实验", "date": D(45), "done": False, "active": True},
            {"name": "中期检查", "date": D(80), "done": False},
            {"name": "学位论文答辩", "date": "2027-05-30", "done": False},
        ],
        "logs": [
            {"date": D(-3), "type": "组会", "content": "汇报多模态融合模型的消融实验结果。教师意见：对比实验缺少仅有音频的 baseline，需补做；融合权重建议改用可学习参数并做敏感性分析。"},
            {"date": D(-16), "type": "个别指导", "content": "讨论期刊投稿方向，确定目标为 IEEE TAFFC（二区）。学生认领投稿格式整理与图表重绘任务。"},
            {"date": D(-40), "type": "组会", "content": "完成数据预处理流程，样本量 480 例。教师提醒注意类别不平衡问题，建议引入加权损失。"},
        ],
    },
    {
        "id": "s2",
        "name": "王雪",
        "degree": "博士",
        "grade": "2023 级",
        "direction": "医学图像分割与可解释性",
        "email": "wangxue23@university.edu.cn",
        "thesisTitle": "弱监督医学图像分割的可解释性建模研究",
        "stage": "论文撰写",
        "progress": 72,
        "nextMeeting": D(4),
        "milestones": [
            {"name": "综合考试", "date": "2024-06-15", "done": True},
            {"name": "开题报告", "date": "2024-11-20", "done": True},
            {"name": "小论文 1（SCI 二区）", "date": "2025-12-01", "done": True},
            {"name": "小论文 2 投稿", "date": D(60), "done": False, "active": True},
            {"name": "学位论文答辩", "date": "2027-06-15", "done": False},
        ],
        "logs": [
            {"date": D(-2), "type": "个别指导", "content": "第二篇论文（可解释性模块）完成初稿，逐段修改引言与方法部分。教师建议补充与 Grad-CAM 等主流方法的定量对比。"},
            {"date": D(-21), "type": "组会", "content": "汇报实验进展，在公开数据集上 Dice 提升 2.3%。教师要求做统计显著性检验。"},
        ],
    },
    {
        "id": "s3",
        "name": "张伟",
        "degree": "硕士",
        "grade": "2023 级",
        "direction": "毫米波雷达行为识别",
        "email": "zhangwei23@university.edu.cn",
        "thesisTitle": "低分辨率雷达点云中的跌倒检测算法研究",
        "stage": "答辩准备",
        "progress": 92,
        "nextMeeting": D(1),
        "milestones": [
            {"name": "开题报告", "date": "2024-05-18", "done": True},
            {"name": "中期检查", "date": "2025-05-12", "done": True},
            {"name": "小论文发表", "date": "2025-09-15", "done": True},
            {"name": "预答辩", "date": D(20), "done": False, "active": True},
            {"name": "学位论文答辩", "date": D(42), "done": False},
        ],
        "logs": [
            {"date": D(-1), "type": "个别指导", "content": "审查学位论文终稿，重点核对第二章相关工作与第四章实验的一致性。教师指出第 4.3 节的指标口径需与公开数据集对齐，避免夸大。"},
            {"date": D(-9), "type": "组会", "content": "完整预演答辩 PPT，时长 22 分钟。教师建议压缩背景介绍，突出方法创新点与实测结果。"},
            {"date": D(-25), "type": "个别指导", "content": "讨论就业与答辩时间安排，提醒留意学位办的材料提交截止日期。"},
        ],
    },
    {
        "id": "s4",
        "name": "陈静",
        "degree": "硕士",
        "grade": "2025 级",
        "direction": "网络流量异常检测",
        "email": "chenjing25@university.edu.cn",
        "thesisTitle": "基于 MoE 架构的加密流量异常检测方法研究",
        "stage": "文献调研",
        "progress": 28,
        "nextMeeting": D(3),
        "milestones": [
            {"name": "开题报告", "date": D(120), "done": False, "active": True},
            {"name": "文献综述", "date": D(60), "done": False},
            {"name": "方法设计与实验", "date": D(260), "done": False},
            {"name": "中期检查", "date": D(380), "done": False},
            {"name": "学位论文答辩", "date": "2028-05-25", "done": False},
        ],
        "logs": [
            {"date": D(-5), "type": "个别指导", "content": "确定选题方向为加密流量异常检测，结合 MoE 稀疏专家思路。教师布置精读 5 篇 NeurlPS/ICLR 近两年论文，下次组会逐一讲解。"},
        ],
    },
]

EVENTS = [
    {"id": "e1", "title": "课题组例会", "type": "组会", "date": D(0), "start": "14:00", "end": "16:00", "location": "信息楼 A-513", "note": "学生汇报近期进展，陈静首次文献分享", "done": False},
    {"id": "e2", "title": "计算机网络（第 03 讲）", "type": "上课", "date": D(0), "start": "10:00", "end": "11:40", "location": "一教 302", "note": "运输层与 TCP 拥塞控制", "done": True},
    {"id": "e3", "title": "国家自然科学基金结题材料提交", "type": "申报", "date": D(5), "start": "09:00", "end": "17:00", "location": "科研处", "note": "p1 中期材料、经费决算表", "done": False},
    {"id": "e4", "title": "硕士预答辩（张伟）", "type": "答辩", "date": D(20), "start": "15:00", "end": "16:00", "location": "信息楼 B-208", "note": "需提前 3 天提交论文电子版", "done": False},
    {"id": "e5", "title": "机器学习导论（第 06 讲）", "type": "上课", "date": D(1), "start": "08:00", "end": "09:40", "location": "研教楼 501", "note": "注意力机制与 Transformer", "done": False},
    {"id": "e6", "title": "院学术委员会会议", "type": "会议", "date": D(2), "start": "16:00", "end": "17:30", "location": "学院会议室", "note": "评审青年基金申报材料", "done": False},
    {"id": "e7", "title": "智能感知学术研讨会", "type": "会议", "date": D(12), "start": "09:00", "end": "17:00", "location": "市会议中心", "note": "作分会场报告", "done": False},
    {"id": "e8", "title": "项目 p3 甲方联调会", "type": "会议", "date": D(7), "start": "10:30", "end": "12:00", "location": "线上（腾讯会议）", "note": "边端部署方案确认", "done": False},
    {"id": "e9", "title": "本科毕业设计选题宣讲", "type": "上课", "date": D(9), "start": "14:00", "end": "15:30", "location": "一教 108", "note": "面向 2023 级本科生", "done": False},
    {"id": "e10", "title": "Python 程序设计（第 01 讲）", "type": "上课", "date": D(-1), "start": "14:00", "end": "15:40", "location": "机房 3", "note": "环境搭建与基础语法", "done": True},
]

TODOS = [
    {"id": "t1", "title": "审阅张伟学位论文终稿并反馈修改意见", "due": D(0), "priority": "high", "done": False, "tag": "学生指导"},
    {"id": "t2", "title": "完成 p1 中期检查材料的经费决算部分", "due": D(3), "priority": "high", "done": False, "tag": "科研项目"},
    {"id": "t3", "title": "准备机器学习课第 07 讲课件（无监督学习）", "due": D(4), "priority": "mid", "done": False, "tag": "课程资源"},
    {"id": "t4", "title": "精读 MoE 多域学习论文并整理笔记", "due": D(2), "priority": "mid", "done": False, "tag": "文献阅读"},
    {"id": "t5", "title": "回复学院关于研究生招生名额的邮件", "due": D(0), "priority": "low", "done": True, "tag": "行政事务"},
    {"id": "t6", "title": "整理 p2 结题验收的现场数据报告", "due": D(-1), "priority": "high", "done": False, "tag": "科研项目"},
]

EXCHANGES = [
    {
        "id": "x1", "title": "智能感知与多模态学习前沿论坛",
        "kind": "学术会议", "role": "分会场报告",
        "organizer": "中国自动化学会 · 智能感知专委会",
        "location": "上海国际会议中心", "level": "国际",
        "start": D(12), "end": D(14),
        "status": "已确认", "funding": "会议注册费 1800 元（项目 p1 支出）",
        "topic": "作「多模态融合在社区精神健康筛查中的实践」分会场报告，时长 20 分钟。",
        "note": "需在会前 5 天提交报告摘要；同期关注雷达感知分论坛，与 p2 相关。",
        "travel": "10/15 高铁 虹桥，10/17 返程",
        "participants": ["江先亮", "王雪"],
    },
    {
        "id": "x2", "title": "IEEE TPAMI 审稿邀请（多模态表征方向）",
        "kind": "期刊审稿", "role": "审稿人",
        "organizer": "IEEE TPAMI 编辑部",
        "location": "线上", "level": "国际",
        "start": D(5), "end": D(26),
        "status": "进行中", "funding": "—",
        "topic": "稿件编号 TPAMI-2026-0412，主题为跨模态对齐的鲁棒性问题。",
        "note": "已完成第一轮意见撰写，待给出最终推荐（minor revision）。",
        "travel": "",
        "participants": ["江先亮"],
    },
    {
        "id": "x3", "title": "国家自然科学基金青年项目通信评议",
        "kind": "基金评审", "role": "通信评议专家",
        "organizer": "国家自然科学基金委员会",
        "location": "线上评议系统", "level": "国家级",
        "start": D(-8), "end": D(18),
        "status": "进行中", "funding": "评审费按件计",
        "topic": "本年度分配 6 份青年基金申请书，方向集中在智能感知与医疗 AI。",
        "note": "已完成 4 份，剩余 2 份需在本月底前提交，注意回避制度。",
        "travel": "",
        "participants": ["江先亮"],
    },
    {
        "id": "x4", "title": "校企联合实验室技术交流（海康威视）",
        "kind": "企业交流", "role": "主讲",
        "organizer": "海康威视研究院",
        "location": "杭州滨江", "level": "企业",
        "start": D(34), "end": D(35),
        "status": "待确认", "funding": "差旅由对方承担",
        "topic": "介绍课题组在低分辨率点云跌倒检测上的工程落地经验。",
        "note": "初步接洽横向合作意向，探索 p2 成果的产品化路径。",
        "travel": "拟 11/8 出发",
        "participants": ["江先亮", "张伟"],
    },
    {
        "id": "x5", "title": "2026 中国计算机大会（CNCC）",
        "kind": "学术会议", "role": "参会",
        "organizer": "中国计算机学会",
        "location": "深圳会展中心", "level": "国内",
        "start": D(-22), "end": D(-19),
        "status": "已完成", "funding": "差旅 4200 元（科研业务费）",
        "topic": "参加「多模态大模型」与「具身智能」专题论坛，与 3 位同行建立联系。",
        "note": "已整理会议纪要，其中稀疏专家路由的工业落地案例对 p3 有参考价值。",
        "travel": "已完成",
        "participants": ["江先亮"],
    },
]

TEACHINGS = [
    {
        "id": "g1", "name": "计算机网络", "code": "CS301",
        "semester": "2026 春", "students": 86, "hours": "56",
        "type": "本科生专业课", "stage": "进行中",
        "syllabusDone": 6, "syllabusTotal": 8,
        "examType": "闭卷考试 + 课程设计",
        "evalScore": "4.72 / 5.0",
        "tasks": [
            {"name": "第 06 讲课件定稿", "due": D(4), "done": False},
            {"name": "期中作业批改", "due": D(9), "done": False},
            {"name": "实验二指导书更新", "due": D(-6), "done": True},
            {"name": "课程设计选题发布", "due": D(16), "done": False},
        ],
        "note": "本学期新增 TCP BBRv3 实测案例，学生反馈良好；期末需提交课程目标达成度分析报告。",
    },
    {
        "id": "g2", "name": "机器学习导论", "code": "CS405",
        "semester": "2026 春", "students": 62, "hours": "48",
        "type": "研究生学位课", "stage": "进行中",
        "syllabusDone": 5, "syllabusTotal": 8,
        "examType": "课程项目答辩",
        "evalScore": "4.85 / 5.0",
        "tasks": [
            {"name": "第 07 讲（无监督学习）备课", "due": D(4), "done": False},
            {"name": "课程项目中期检查", "due": D(13), "done": False},
            {"name": "Guest Lecture 邀请（企业专家）", "due": D(20), "done": False},
        ],
        "note": "计划邀请海康研究院专家做一次产业前沿讲座；项目答辩拟安排在期末前两周。",
    },
    {
        "id": "g3", "name": "Python 程序设计", "code": "CS102",
        "semester": "2026 秋", "students": 124, "hours": "48",
        "type": "本科生基础课", "stage": "备课中",
        "syllabusDone": 1, "syllabusTotal": 8,
        "examType": "机考 + 综合项目",
        "evalScore": "—",
        "tasks": [
            {"name": "教学大纲终稿提交", "due": D(-2), "done": True},
            {"name": "实验环境镜像制作", "due": D(30), "done": False},
            {"name": "第 01-02 讲课件准备", "due": D(35), "done": False},
        ],
        "note": "大班教学（124 人），助教需求已上报；拟采用在线判题系统降低批改负担。",
    },
    {
        "id": "g4", "name": "本科毕业设计（2023 级）", "code": "THESIS-2023",
        "semester": "2026 春", "students": 8, "hours": "—",
        "type": "毕业设计指导", "stage": "选题阶段",
        "syllabusDone": 0, "syllabusTotal": 1,
        "examType": "论文 + 答辩",
        "evalScore": "—",
        "tasks": [
            {"name": "选题宣讲与意向登记", "due": D(9), "done": False},
            {"name": "开题报告审核", "due": D(45), "done": False},
        ],
        "note": "拟提供 4 个多模态/雷达感知方向选题，其余由学生自拟后审定。",
    },
]

ACHIEVEMENTS = [
    {
        "id": "a1", "title": "基于点云时序建模的毫米波雷达跌倒检测方法",
        "type": "期刊论文", "level": "SCI 二区",
        "authors": "江先亮, 张伟, 李明", "role": "第一作者",
        "venue": "IEEE Sensors Journal", "date": "2025-09-15",
        "status": "已发表", "score": 8.0,
        "projectId": "p2", "doi": "10.1109/JSEN.2025.3412210",
        "note": "提出点云时序编码 + 轻量检测头，在自建数据集上 F1 达 0.961；被后续 3 篇工作引用。",
    },
    {
        "id": "a2", "title": "多模态对比学习在精神分裂症早期识别中的应用",
        "type": "期刊论文", "level": "SCI 二区",
        "authors": "江先亮, 李明, 王雪", "role": "第一作者",
        "venue": "IEEE Transactions on Affective Computing", "date": "2025-11-20",
        "status": "已录用", "score": 8.0,
        "projectId": "p1", "doi": "—",
        "note": "融合面部微表情、语音韵律与临床量表三模态，AUC 0.887，显著优于单模态基线。",
    },
    {
        "id": "a3", "title": "基于教师学生网络的电梯故障预测方法及系统",
        "type": "发明专利", "level": "发明专利",
        "authors": "江先亮, 陈静", "role": "第一发明人",
        "venue": "国家知识产权局", "date": "2026-02-18",
        "status": "已授权", "score": 6.0,
        "projectId": "p3", "doi": "ZL202410987654.3",
        "note": "已应用于两家物业的 36 台电梯，故障提前预警平均提前 11 天。",
    },
    {
        "id": "a4", "title": "智慧养老跌倒监测系统 V1.0",
        "type": "软件著作权", "level": "软著",
        "authors": "江先亮, 张伟", "role": "第一完成人",
        "venue": "中国版权保护中心", "date": "2025-04-08",
        "status": "已登记", "score": 3.0,
        "projectId": "p2", "doi": "2025SR0456781",
        "note": "含雷达数据采集、跌倒判别与告警推送三个模块，已在 2 个社区试用。",
    },
    {
        "id": "a5", "title": "融合语音韵律的阴性症状评估方法研究",
        "type": "期刊论文", "level": "SCI 三区",
        "authors": "李明, 江先亮", "role": "通讯作者",
        "venue": "Biomedical Signal Processing and Control", "date": "2026-05-12",
        "status": "审稿中", "score": 5.0,
        "projectId": "p1", "doi": "—",
        "note": "第一轮审稿意见已返回，需补充跨中心泛化实验，预计 3 周内修回。",
    },
    {
        "id": "a6", "title": "多模态融合社区精神健康筛查关键技术及应用",
        "type": "科技奖励", "level": "省部级二等奖",
        "authors": "江先亮 等", "role": "第一完成人",
        "venue": "省科学技术厅", "date": "2026-01-10",
        "status": "已获奖", "score": 10.0,
        "projectId": "p1", "doi": "—",
        "note": "依托 p1 阶段性成果申报，已完成成果登记与奖金分配。",
    },
    {
        "id": "a7", "title": "断路器分合闸声纹的时频特征与缺陷识别",
        "type": "期刊论文", "level": "EI 期刊",
        "authors": "江先亮, 王雪", "role": "第二作者",
        "venue": "电工技术学报", "date": "",
        "status": "撰写中", "score": 3.0,
        "projectId": "p4", "doi": "—",
        "note": "已完成实验与初稿，待补充现场验证数据后投稿。",
    },
    {
        "id": "a8", "title": "面向养老场景的雷达感知关键技术研究",
        "type": "学位论文", "level": "校级优秀硕士论文",
        "authors": "张伟（指导教师：江先亮）", "role": "指导教师",
        "venue": "本校研究生院", "date": D(42),
        "status": "申报中", "score": 2.0,
        "projectId": "p2", "doi": "—",
        "note": "拟在张伟答辩后申报校级优秀学位论文，需提前准备推荐材料。",
    },
]

DEVELOPMENTS = [
    {
        "id": "d1", "title": "教授职称聘期考核（2026-2029）",
        "category": "职称晋升", "status": "进行中",
        "start": "2026-01-01", "deadline": D(420),
        "progress": 35,
        "target": "聘期内完成：主持国家级项目 1 项、一区论文 2 篇、省部级奖励 1 项",
        "current": "已主持在研国家级项目 1 项；二区论文 1 篇已录用；省部级二等奖已获",
        "note": "考核以聘期目标为准，建议每年度自评一次并留档佐证材料。",
        "metrics": [
            {"name": "主持国家级项目", "target": 1, "current": 1, "unit": "项"},
            {"name": "高水平论文（二区及以上）", "target": 2, "current": 1, "unit": "篇"},
            {"name": "省部级及以上奖励", "target": 1, "current": 1, "unit": "项"},
        ],
    },
    {
        "id": "d2", "title": "国家自然科学基金杰出青年科学基金申报",
        "category": "人才项目", "status": "准备中",
        "start": D(60), "deadline": D(300),
        "progress": 12,
        "target": "2027 年度申报，需系统性整合多模态感知方向的系列成果",
        "current": "已完成方向梳理，待补充代表性成果的引用数据",
        "note": "需提前与学院沟通申报意向；建议邀请 2 位同行专家做预评审。",
        "metrics": [
            {"name": "代表性论文", "target": 5, "current": 2, "unit": "篇"},
            {"name": "同行推荐意见", "target": 3, "current": 0, "unit": "份"},
        ],
    },
    {
        "id": "d3", "title": "研究生导师年度培训（立德树人专题）",
        "category": "培训进修", "status": "已完成",
        "start": D(-45), "deadline": D(-20),
        "progress": 100,
        "target": "完成 16 学时导师培训并通过考核",
        "current": "已完成全部学时，取得结业证书",
        "note": "培训材料已归档；其中「研究生心理支持」模块对学生指导工作有直接帮助。",
        "metrics": [
            {"name": "培训学时", "target": 16, "current": 16, "unit": "学时"},
        ],
    },
    {
        "id": "d4", "title": "企业挂职锻炼（拟：海康威视研究院）",
        "category": "产学研", "status": "规划中",
        "start": D(120), "deadline": D(300),
        "progress": 5,
        "target": "累计 3 个月企业实践，建立稳定的校企合作通道",
        "current": "已初步接洽，待学校审批",
        "note": "挂职期间需兼顾在研项目进度，拟安排青年教师协助带教。",
        "metrics": [
            {"name": "实践时长", "target": 3, "current": 0, "unit": "月"},
        ],
    },
    {
        "id": "d5", "title": "年度个人教学科研述职与规划",
        "category": "考核述职", "status": "进行中",
        "start": D(-10), "deadline": D(26),
        "progress": 60,
        "target": "完成上一年度教学、科研、服务三方面述职报告",
        "current": "教学与科研部分已完成，社会服务数据待汇总",
        "note": "述职报告需附成果佐证清单，建议与成果管理模块数据对齐。",
        "metrics": [
            {"name": "述职报告完成度", "target": 100, "current": 60, "unit": "%"},
        ],
    },
]

TOOLS = [
    {"id": "k1", "name": "教学日历编排", "category": "教学", "desc": "按教学周自动生成课程进度表，支持节假日顺延与调课标记。", "url": "internal://teaching-calendar", "freq": 12, "builtin": True},
    {"id": "k2", "name": "成绩批量计算", "category": "教学", "desc": "导入平时/期中/期末成绩，按权重自动合成总评并导出成绩单。", "url": "internal://grade-calc", "freq": 6, "builtin": True},
    {"id": "k3", "name": "参考文献格式转换", "category": "科研", "desc": "BibTeX / RIS / GB/T 7714 三种格式互转，支持批量处理。", "url": "internal://cite-convert", "freq": 18, "builtin": True},
    {"id": "k4", "name": "经费预算测算", "category": "科研", "desc": "按设备费/材料费/差旅费等科目测算项目预算，自动校验比例限制。", "url": "internal://budget-calc", "freq": 4, "builtin": True},
    {"id": "k5", "name": "论文投稿进度追踪", "category": "科研", "desc": "记录投稿期刊、审稿状态与关键时间节点，逾期自动提醒。", "url": "internal://submission-track", "freq": 9, "builtin": True},
    {"id": "k6", "name": "研究生培养进度看板", "category": "学生", "desc": "汇总各学生的论文阶段、里程碑达成与沟通记录，一屏总览。", "url": "internal://student-board", "freq": 15, "builtin": True},
    {"id": "k7", "name": "值班与调课登记", "category": "教学", "desc": "登记调课、代课与监考安排，自动生成变更通知。", "url": "internal://duty-log", "freq": 3, "builtin": True},
    {"id": "k8", "name": "学术会议纪要模板", "category": "科研", "desc": "标准化的会议纪要模板，含议题、结论、待办三栏结构。", "url": "internal://meeting-note", "freq": 7, "builtin": True},
    {"id": "k9", "name": "PDF 批量合并与拆分", "category": "文档", "desc": "合并多份 PDF 或按页码范围拆分为独立文件，适合材料申报。", "url": "internal://pdf-toolkit", "freq": 5, "builtin": True},
    {"id": "k10", "name": "科研成果统计导出", "category": "科研", "desc": "按年度/类型导出成果清单，格式对齐学校考核模板。", "url": "internal://achievement-export", "freq": 2, "builtin": True},
    {"id": "k11", "name": "课件 PPT 风格统一", "category": "教学", "desc": "生成课件样式规范方案与检查清单，保持全课程视觉一致。", "url": "internal://ppt-theme", "freq": 8, "builtin": True},
    {"id": "k12", "name": "实验室设备借用登记", "category": "行政", "desc": "记录设备借用与归还情况，支持逾期提醒与责任人追溯。", "url": "internal://device-lend", "freq": 10, "builtin": True},
]

# 首页底部「常用网站」的出厂清单：教师可增删改，图标由服务端自动抓取
LINKS = [
    {"id": "w1", "name": "中国知网", "url": "https://www.cnki.net", "group": "学术资源",
     "note": "中文期刊全文检索与下载", "sort": 0},
    {"id": "w2", "name": "万方数据", "url": "https://www.wanfangdata.com.cn", "group": "学术资源",
     "note": "期刊 / 学位论文 / 会议文献", "sort": 1},
    {"id": "w3", "name": "百度学术", "url": "https://xueshu.baidu.com", "group": "学术资源",
     "note": "跨库检索与引文追踪", "sort": 2},
    {"id": "w4", "name": "arXiv", "url": "https://arxiv.org", "group": "学术资源",
     "note": "预印本，跟进最新方法", "sort": 3},
    {"id": "w5", "name": "国家科技图书文献中心", "url": "https://www.nstl.gov.cn", "group": "学术资源",
     "note": "外文文献检索与代查代借", "sort": 4},
    {"id": "w6", "name": "中国大学 MOOC", "url": "https://www.icourse163.org", "group": "教学平台",
     "note": "课程建设与优质课参考", "sort": 5},
    {"id": "w7", "name": "学堂在线", "url": "https://www.xuetangx.com", "group": "教学平台",
     "note": "慕课资源与混合式教学", "sort": 6},
    {"id": "w8", "name": "国家自然科学基金委", "url": "https://www.nsfc.gov.cn", "group": "科研工具",
     "note": "项目指南、申报与结题", "sort": 7},
    {"id": "w9", "name": "专利检索及分析系统", "url": "https://pss-system.cponline.cnipa.gov.cn",
     "group": "科研工具", "note": "专利查新与侵权检索", "sort": 8},
    {"id": "w10", "name": "GitHub", "url": "https://github.com", "group": "科研工具",
     "note": "代码托管与开源项目", "sort": 9},
    {"id": "w11", "name": "中国研究生招生信息网", "url": "https://yz.chsi.com.cn", "group": "公共服务",
     "note": "招生政策与调剂信息", "sort": 10},
    {"id": "w12", "name": "教育部", "url": "https://www.moe.gov.cn", "group": "公共服务",
     "note": "教育政策与文件查询", "sort": 11},
]

COLLECTION_SEED = {
    "projects": PROJECTS,
    "literature": LITERATURE,
    "courses": COURSES,
    "students": STUDENTS,
    "events": EVENTS,
    "todos": TODOS,
    "exchanges": EXCHANGES,
    "teachings": TEACHINGS,
    "achievements": ACHIEVEMENTS,
    "developments": DEVELOPMENTS,
    "tools": TOOLS,
    "tool_runs": [],
    "links": LINKS,
}


def full_seed() -> dict:
    """返回 {profile, <collection>: [...]} 的完整种子副本。"""
    import copy

    data = {k: copy.deepcopy(v) for k, v in COLLECTION_SEED.items()}
    data["profile"] = copy.deepcopy(PROFILE)
    return data
